/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dlogic_uFCoder */

#ifndef _Included_com_dlogic_uFCoder
#define _Included_com_dlogic_uFCoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderOpen
  (JNIEnv *, jclass);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderOpenEx
 * Signature: (ILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderOpenEx
  (JNIEnv *, jclass, jint, jstring, jint, jstring);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderReset
  (JNIEnv *, jclass);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderClose
  (JNIEnv *, jclass);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetReaderType
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetReaderType
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetReaderSerialNumber
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetReaderSerialNumber
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetReaderFirmwareVersion
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetReaderFirmwareVersion
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetReaderHardwareVersion
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetReaderHardwareVersion
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetBuildNumber
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetBuildNumber
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderStillConnected
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderStillConnected
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GreenLedBlinkingTurnOff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GreenLedBlinkingTurnOff
  (JNIEnv *, jclass);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    ReaderUISignal
 * Signature: (BB)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_ReaderUISignal
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetCardIdEx
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetCardIdEx
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    GetDlogicCardType
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_GetDlogicCardType
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    SetISO14443_4_Mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_SetISO14443_14_1Mode
  (JNIEnv *, jclass);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    s_block_deselect
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_s_1block_1deselect
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    EMV_GetPAN
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_dlogic_uFCoder_EMV_1GetPAN
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_dlogic_uFCoder
 * Method:    UFR_Status2String
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dlogic_uFCoder_UFR_1Status2String
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
